"use client"

import Link from 'next/link'
import { Download, Eye, Search } from 'lucide-react'
import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'

export default function InvoicesPage() {
  const { t, i18n } = useTranslation();
  const [mounted, setMounted] = useState(false);
  
  // Only show the fully translated content after mounting on the client
  // This prevents hydration mismatch between server and client
  useEffect(() => {
    setMounted(true);
  }, []);
  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">
          {mounted ? t('invoicesTitle') : (i18n.language === 'ja' ? '請求書管理' : 'Invoices')}
        </h1>
        <div className="text-sm text-gray-600 bg-blue-50 p-2 rounded-md">
          {mounted ? t('invoicesAutoGenerated') : (i18n.language === 'ja' ? '請求書は注文が確認されると自動的に生成されます' : 'Invoices are automatically generated when orders are confirmed')}
        </div>
      </div>

      {/* Search and Filter */}
      <div className="bg-white rounded-lg shadow p-4 mb-6">
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-grow">
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search size={18} className="text-gray-400" />
              </div>
              <input
                type="text"
                placeholder={mounted ? t('searchInvoices') + '...' : (i18n.language === 'ja' ? '請求書番号、顧客名で検索...' : 'Search by invoice number, customer name...')}
                className="form-input pl-10"
              />
            </div>
          </div>
          <div className="w-full md:w-48">
            <select className="form-select">
              <option value="">
                {mounted ? t('allDivisions') : (i18n.language === 'ja' ? 'すべての部門' : 'All Divisions')}
              </option>
              <option value="sewing">
                {mounted ? t('sewingDivision') : (i18n.language === 'ja' ? '縫製部門' : 'Sewing Division')}
              </option>
              <option value="interior">
                {mounted ? t('interiorDivision') : (i18n.language === 'ja' ? 'インテリア部門' : 'Interior Division')}
              </option>
            </select>
          </div>
          <div className="w-full md:w-48">
            <select className="form-select">
              <option value="">
                {mounted ? t('allStatuses') : (i18n.language === 'ja' ? 'すべてのステータス' : 'All Statuses')}
              </option>
              <option value="draft">
                {mounted ? t('draft') : (i18n.language === 'ja' ? '下書き' : 'Draft')}
              </option>
              <option value="sent">
                {mounted ? t('sent') : (i18n.language === 'ja' ? '送信済み' : 'Sent')}
              </option>
              <option value="paid">
                {mounted ? t('paid') : (i18n.language === 'ja' ? '支払済み' : 'Paid')}
              </option>
              <option value="overdue">
                {mounted ? t('overdue') : (i18n.language === 'ja' ? '期限超過' : 'Overdue')}
              </option>
            </select>
          </div>
        </div>
      </div>

      {/* Invoices Table */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('invoiceNumber') : (i18n.language === 'ja' ? '請求書番号' : 'Invoice Number')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('customerName') : (i18n.language === 'ja' ? '顧客' : 'Customer')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('division') : (i18n.language === 'ja' ? '部門' : 'Division')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('amount') : (i18n.language === 'ja' ? '金額' : 'Amount')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('issueDate') : (i18n.language === 'ja' ? '発行日' : 'Issue Date')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('dueDate') : (i18n.language === 'ja' ? '支払期限' : 'Due Date')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('status') : (i18n.language === 'ja' ? 'ステータス' : 'Status')}
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                {mounted ? t('actions') : (i18n.language === 'ja' ? '操作' : 'Actions')}
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {/* Sample Invoice 1 */}
            <tr>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">INV-20250705-1234</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">{mounted ? t('tanakaTaro') : (i18n.language === 'ja' ? '田中太郎' : 'Tanaka Taro')}</div>
                <div className="text-sm text-gray-500">{mounted ? t('tanakaShoji') : (i18n.language === 'ja' ? '田中商事' : 'Tanaka Shoji')}</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">
                  {mounted ? t('sewingDivision') : (i18n.language === 'ja' ? '縫製部門' : 'Sewing Division')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">¥82,500</div>
                <div className="text-xs text-gray-500">
                  {mounted ? t('taxIncluded') : (i18n.language === 'ja' ? '（税込）' : '(Tax Included)')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/07/05</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/08/04</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="status-sent">{mounted ? t('sent') : (i18n.language === 'ja' ? '送信済み' : 'Sent')}</span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                <div className="flex space-x-2">
                  <Link href="/invoices/1" className="text-blue-600 hover:text-blue-900">
                    <Eye size={18} />
                  </Link>
                  <Link href="/invoices/1/download" className="text-blue-600 hover:text-blue-900">
                    <Download size={18} />
                  </Link>
                </div>
              </td>
            </tr>

            {/* Sample Invoice 2 */}
            <tr>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">INV-20250701-5678</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">{mounted ? t('satoHanako') : (i18n.language === 'ja' ? '佐藤花子' : 'Sato Hanako')}</div>
                <div className="text-sm text-gray-500">{mounted ? t('satoKogyo') : (i18n.language === 'ja' ? '佐藤工業' : 'Sato Kogyo')}</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">
                  {mounted ? t('interiorDivision') : (i18n.language === 'ja' ? 'インテリア部門' : 'Interior Division')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">¥137,500</div>
                <div className="text-xs text-gray-500">
                  {mounted ? t('taxIncluded') : (i18n.language === 'ja' ? '（税込）' : '(Tax Included)')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/07/01</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/07/31</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="status-paid">{mounted ? t('paid') : (i18n.language === 'ja' ? '支払済み' : 'Paid')}</span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                <div className="flex space-x-2">
                  <Link href="/invoices/2" className="text-blue-600 hover:text-blue-900">
                    <Eye size={18} />
                  </Link>
                  <Link href="/invoices/2/download" className="text-blue-600 hover:text-blue-900">
                    <Download size={18} />
                  </Link>
                </div>
              </td>
            </tr>

            {/* Sample Invoice 3 */}
            <tr>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">INV-20250628-9012</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">{mounted ? t('yamadaJiro') : (i18n.language === 'ja' ? '山田次郎' : 'Yamada Jiro')}</div>
                <div className="text-sm text-gray-500">{mounted ? t('yamadaDesign') : (i18n.language === 'ja' ? '山田デザイン' : 'Yamada Design')}</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">
                  {mounted ? t('sewingDivision') : (i18n.language === 'ja' ? '縫製部門' : 'Sewing Division')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">¥49,500</div>
                <div className="text-xs text-gray-500">
                  {mounted ? t('taxIncluded') : (i18n.language === 'ja' ? '（税込）' : '(Tax Included)')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/06/28</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/07/28</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="status-paid">{mounted ? t('paid') : (i18n.language === 'ja' ? '支払済み' : 'Paid')}</span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                <div className="flex space-x-2">
                  <Link href="/invoices/3" className="text-blue-600 hover:text-blue-900">
                    <Eye size={18} />
                  </Link>
                  <Link href="/invoices/3/download" className="text-blue-600 hover:text-blue-900">
                    <Download size={18} />
                  </Link>
                </div>
              </td>
            </tr>

            {/* Sample Invoice 4 */}
            <tr>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">INV-20250615-3456</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm font-medium text-gray-900">{mounted ? t('satoHanako') : (i18n.language === 'ja' ? '佐藤花子' : 'Sato Hanako')}</div>
                <div className="text-sm text-gray-500">{mounted ? t('satoKogyo') : (i18n.language === 'ja' ? '佐藤工業' : 'Sato Kogyo')}</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">
                  {mounted ? t('interiorDivision') : (i18n.language === 'ja' ? 'インテリア部門' : 'Interior Division')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900">¥55,000</div>
                <div className="text-xs text-gray-500">
                  {mounted ? t('taxIncluded') : (i18n.language === 'ja' ? '（税込）' : '(Tax Included)')}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/06/15</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-500">2025/07/15</div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="status-overdue">期限超過</span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                <div className="flex space-x-2">
                  <Link href="/invoices/4" className="text-blue-600 hover:text-blue-900">
                    <Eye size={18} />
                  </Link>
                  <Link href="/invoices/4/download" className="text-blue-600 hover:text-blue-900">
                    <Download size={18} />
                  </Link>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        
        {/* Pagination */}
        <div className="bg-white px-4 py-3 border-t border-gray-200 sm:px-6">
          <div className="flex items-center justify-between">
            <div className="text-sm text-gray-700">
              全 <span className="font-medium">36</span> 件中 <span className="font-medium">1</span> から <span className="font-medium">10</span> 件を表示
            </div>
            <div className="flex-1 flex justify-end">
              <button className="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed" disabled>
                前へ
              </button>
              <button className="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
                次へ
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
